### ISSUE TITLE
[NULL]

### ISSUE THREAD

**Issue by OfficerPotato911** [eln2/eln2#214] opened 2022-06-29 05:13 UTC
In ELN1 wiring can be frustrating - Only base Minecraft blocks could cover up the wires for example and they were just impossible to hide. 

Please allow blocks from Chisel to be used to cover wires! 
Also; a way to have a component "Centrally-Wired" would be nice. The concept here is a wire is inside of a wall, hidden. you could place a component - Like a light switch, lighting fixture or some member of the Signals family like a motion sensor - on your wall or ceiling and connect to that wire "from the back" of the thing. This would allow more clean-looking bases in certain applications where the hiding of the wires would be preferred.

I've said this before in Discord and it was mentioned that there could be a problem if the block behind the equipment has multiple wires. This is where I'm thinking this feature could require a different block - similar to a Hub. You place said component inside the wall and connect it to the wire you want. It would behave like a generic cable hub but would be what the component connects to.

In ELN1 when placing light fixtures, if you typed a wireless channel it seemed to save it but if you were powering with a cable it didn't remember that option - for those who wire with cable it's a pain to go one-by-one and change that option.

I could think of an evil way to dodge voltage drop by using lamp supplies and outlets - There seems to be no drop between a lamp supply and a load connected to it. Cmon this is ELN we're talking about here, such a easy way of escaping the stubborn-ness of electricity isn't tolerable! :p

**Comment by jrddunbr** [comment] 2022-06-29 05:31
> Please allow blocks from Chisel to be used to cover wires!

This actually worked (somewhat) in the fork, except for situations where we had connected textures issues.

The rest of this is a duplicate of https://github.com/age-series/ElectricalAge2/issues/131, we have a lot of ideas about using conduits.

Yes, ELN1 lamp supplies and outlets are super broken and OP. It's actually one of the most efficient ways to move power, I think it can move more than poles. Wirelessly. Lol.. that system is 100% getting replaced with conduits.

**Closed as completed by jrddunbr** 2022-06-29 05:31 UTC
Labels: duplicate

**Comment by OfficerPotato911** [comment] 2022-06-29 05:50
Someone else mentioned the central wiring part?

**Comment by DarthSidiousPalpatine** [comment] 2022-06-29 06:21
Something like that?
![image](https://user-images.githubusercontent.com/21008918/176365672-092aa145-48d0-4075-bbc7-84bddea625d8.png)
![image](https://user-images.githubusercontent.com/21008918/176365714-4ae23620-3391-4ab2-89ab-cea6bc2711cd.png)

Oh, its closed...
