### ISSUE TITLE
Solar Panel Enhancements

### ISSUE THREAD

**Issue by genestrashcan** [eln2/eln2#127] opened 2021-03-20 02:36 UTC
Some enhancements for solar panels with references that should be implemented make them more realistic

**Lifespan**

Solar panels have a lifespan, similar to batteries, there average lifespan is about 35 years, they lose 1% of their output every year based upon a calculation of a average life of 306810 hours at 12 hours of use (sunlight) per day. They lose 1% of their power output every 8766 hours of use. Having a solar panel fail from old age in a set wired in series to stack up and produce high voltage fail can be quite a fireworks show, which would be a reason to group replace them near the end of their lifespan. Sometimes they can also have a chance to randomly fail without warning like lights and motors and other things in real life can do. [ref1](https://urjos.com/will-average-life-solar-panels/)

**Snow and Cold Temperatures**

When Snow accumulates on and near solar panels in cold areas contrary to belief it can increase and even DOUBLE their power output due to the albedo effect of nearby snow reflecting sunlight and also the cold temperatures increasing their efficiency. 
The dark color of solar panels attract heat and help in melting the snow. Solar panels are designed to attract the sun’s rays and trap them. Generally speaking, solar panels are 20°C (36°F) warmer than the ambient temperature. So even a glimmer of sunlight can cause the solar panels to start warming up and hence hasten the melting of snow around them. [ref2](https://www.energy.gov/eere/articles/let-it-snow-how-solar-panels-can-thrive-winter-weather)

**Solar Array and Tower**

Contrary to popular belief a Round Solar Array and Tower is actually a series of mirrors that concentrate the sun's energy into a glass tank filled with water in a tower to heat that water to boiling point to produce large amounts of steam to turn and run a turbine to generate power like a typical steam engine. [ref3](https://en.wikipedia.org/wiki/Solar_power_tower)

**Comment by jrddunbr** [comment] 2021-03-20 02:39
Duplicate of #1, the rest of the features will not happen because meh.

**Closed as completed by jrddunbr** 2021-03-20 02:39 UTC
