### ISSUE TITLE
[NULL]

### ISSUE THREAD

**Issue by OfficerPotato911** [eln2/eln2#215] opened 2022-06-29 05:23 UTC
The addition of spotlights could come in handy in certain applications, such as making custom lights for your parking lot, or lighting up the perimeter of your large castle. This should include spotlight bulbs of certain types, and fixtures which will only accept those bulbs.

Also; if you're planning to add better street lights - ALL HAIL THE SODIUM LAMP!
You should add sodium lamps to spice it up and detail them a little - with them turning on cool and dim and getting warm and bright over time.

Also certain fixtures shouldn't accept some bulbs - I've always been OCD about the fluorescent fixture accepting incandescent bulbs.

**Comment by OfficerPotato911** [comment] 2022-06-29 05:25
![sodium](https://user-images.githubusercontent.com/75597251/176358245-d9a05900-b9d8-4a10-bdbc-37c74e96d13c.png)

**Comment by jrddunbr** [comment] 2022-06-29 05:32
Duplicate of https://github.com/age-series/ElectricalAge2/issues/133

**Closed as completed by jrddunbr** 2022-06-29 05:32 UTC
Labels: duplicate

**Comment by OfficerPotato911** [comment] 2022-06-29 05:49
ah yes I forgot the search for it before you post thing srry
